spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database.platform: org.hibernet.dialect.H2Dialect
    properties.hibernet.show_sql: true
    properties.hibernet.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

